services:
  db:
    image: postgres:17-alpine
    container_name: verzel-elite-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: verzel_elite
      POSTGRES_USER: verzel_elite
      POSTGRES_PASSWORD: verzel_elite

    ports:
      - "5438:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U verzel_elite -d verzel_elite"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: